name: aa20260902 testy

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r src/aa20260902_wymogi.txt

      - name: Uruchomienie testów
        working-directory: src
        run: pytest aa20260902_sattests.py -v